version: "3.8"

services:

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: rikkei_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rikkei_network

  backend:
    image: yourdockerhub/backend
    container_name: spring_backend
    depends_on:
      - db
    networks:
      - rikkei_network

  frontend:
    build: .
    container_name: react_frontend
    ports:
      - "3000:80"
    networks:
      - rikkei_network

volumes:
  postgres_data:

networks:
  rikkei_network: