name: Deploy DevOps Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 3.34.129.103
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "devops-project" ]; then
              git clone https://github.com/quynh410/Devop_Project.git
            fi

            cd devops-project
            git pull origin main

            docker-compose down
            docker-compose up -d --build